version: '3'
services:
  gatekeeper:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - KOTOBA_ID=251239170058616833
      - ANNOUNCEMENT_CHANNEL_ID=617136489482027059
      - TOKEN=...